### ISSUE TITLE
Docgen miscellaneous issues

### ISSUE THREAD

**Issue by philpax** [AmbientRun/Ambient#1187]
- [ ] There are no buttons to copy anything. Not sure how that should work when the package ID will depend on the package you're using it from.
- [ ] Ideally, there's some form of cross-reference, so you can see what uses a given component / type / etc.
- [ ] There's no way to search for items.
