### ISSUE TITLE
Netcode roadmap

### ISSUE THREAD

**Issue by pierd** [AmbientRun/Ambient#671]
If you have a feature request or issue regarding Ambient's networking (netcode), please post it here.

## Now
- [ ] https://github.com/AmbientRun/Ambient/pull/660
- [ ] https://github.com/AmbientRun/Ambient/issues/628
- [ ] https://github.com/AmbientRun/Ambient/issues/627

## Next
- [ ] https://github.com/AmbientRun/Ambient/issues/665
- [ ] https://github.com/AmbientRun/Ambient/issues/664
- [ ] https://github.com/AmbientRun/Ambient/issues/662
- [ ] https://github.com/AmbientRun/Ambient/issues/663

## Later
- [ ] https://github.com/AmbientRun/Ambient/issues/670
- [ ] https://github.com/AmbientRun/Ambient/issues/667
- [ ] https://github.com/AmbientRun/Ambient/issues/666
- [ ] https://github.com/AmbientRun/Ambient/issues/668
- [ ] https://github.com/AmbientRun/Ambient/issues/669

**Comment by pierd** [comment]
https://github.com/ThusSpokeNomad/GameNetworkingResources
