### ISSUE TITLE
Asset pipeline roadmap

### ISSUE THREAD

**Issue by FredrikNoren** [AmbientRun/Ambient#764]
- [ ] Visual/UI pipeline.toml editor (it's quite hard to figure out how to edit the file manually right now)
- [ ] #689
- [ ] UI to browse compiled assets (in the [Ambient IDE](#694)
- [ ] #222
- [ ] A way to directly upload assets on the website
- [ ] #12

**Comment by philpax** [comment]
Regarding the compiled asset browser - could be #1148 and #1151.
