### ISSUE TITLE
Future Tangent features

### ISSUE THREAD

**Issue by philpax** [AmbientRun/Ambient#914]
This is a list of things I'd like to do for Tangent - some of them will have overlap with the building of standard packages. Some of these have already been done in other projects and need to be extracted.

- [ ] Only show crosshair if no UI is open
- [ ] Split vehicle definition from class definition to make it easier to clone the vehicle def onto the vehicles
- [ ] 2D/3D nameplates - they hover over vehicles and show you the player's name and their class
- [ ] Join/leave indicators
- [ ] Killfeed
- [ ] Chat
- [ ] Scoreboard
- [ ] Enhanced class selection - show model to the left of the selection menu?
- [ ] Gamemodes
  - [ ] Capture the Flag
  - [ ] Deathmatch
  - [ ] Team Deathmatch
